---
- name: install development dependencies
  apt:
    name: "{{item}}"
    state: installed
  become: true
  with_items:
    - bash-completion
    - build-essential
    - htop
    - python3-dev
    - python3-flake8
    - python3-pip
    - python3-venv
    - screen

- name: install rsync
  apt:
    name: "{{item}}"
    state: installed
  become: true
  when: source_transport == 'rsync'
  with_items:
    - rsync

- name: install build dependencies
  apt:
    name: "{{item}}"
    state: installed
  become: true
  with_items:
    - git-core

- name: install dependencies
  apt:
    name: "{{item}}"
    state: installed
  become: true
  with_items:
    - vim-nox

