---
# a role that sets up an environment for developing the hub on a ubuntu machine
# it assumes the role `ubuntu-build` has been applied
- name: create user
  become: true
  user:
    name: "{{build_user}}"
    createhome: yes
    shell: /bin/bash
    # set password to '*' to unlock ssh access
    password: $6$loHAn4IfYLEdMc$e0de/845DozoVAzG1rKx8eRqrBxRLnYJO746dqozpxYhxSgCfA7bI9p0KoDqNU8A0hot1zqJvMQNWM1IuJGnx1
    update_password: always
    groups: sudo
    append: yes

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: enable ssh access
  become: true
  authorized_key:
    user: "{{build_user}}"
    key: "{{build_user_key}}"
  when: build_user_key is defined

- name: install dependencies
  apt:
    name: "{{item}}"
    state: installed
  become: true
  with_items:
    - rsync

- name: enable github deploy access
  become: true
  become_user: "{{build_user}}"
  file:
    dest: "/home/{{build_user}}/.ssh"
    mode: "0700"
    owner: "{{build_user}}"
    group: "{{build_user}}"
    state: directory
  when: source_transport == 'git'
  tags: gitco

- name: enable github deploy access
  become: true
  become_user: "{{build_user}}"
  copy:
    src: github_deploy_rsa
    dest: "/home/{{build_user}}/.ssh/id_rsa"
    mode: "0600"
    owner: "{{build_user}}"
    group: "{{build_user}}"
  when: source_transport == 'git'
  tags: gitco

- name: checkout hub sources
  git:
    repo: "git@github.com:tomster/nuimo-hub-backend"
    remote: tomster
    dest: "/home/{{build_user}}/nuimo-hub-backend"
    version: "wifi-onboarding"
    accept_hostkey: true
  become: true
  become_user: "{{build_user}}"
  tags:
    - gitco
    - gitup
  when: source_transport == 'git'

- name: bootstrap development checkout
  become: true
  become_user: "{{build_user}}"
  command: make
  args:
    creates: "/home/{{build_user}}/nuimo-hub-backend/application/venv/bin/python"
    chdir: "/home/{{build_user}}/nuimo-hub-backend/application/"
  tags: gitco
  when: source_transport == 'git'

- name: create hub sources destination
  file:
    dest: "/home/{{build_user}}/nuimo-hub-backend/application"
    state: directory
  become: true
  become_user: "{{build_user}}"
  tags: rsync
  when: source_transport == 'rsync'

- include: vim.yml
  when: configure_vim
  tags: vim
