---
- name: upload missing asyncio to lib/python
  synchronize:
    src: asyncio
    dest: "/usr/lib/python3.5/"
    archive: false
    delete: true
    rsync_opts:
    - "-rlptD"
    - "-e bin/ploy-ssh"
  tags:
    - hass
    - asyncio

- name: create deployment location
  become: true
  file:
    dest: "{{hass_deploy_location}}"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory
  tags: hass

- name: create data location
  become: true
  file:
    dest: "{{hass_data_location}}"
    owner: "{{run_user}}"
    group: "{{run_user}}"
    mode: "0750"
    state: directory
  tags: hass

- name: init virtualenv in deployment location
  command: "{{python_interpreter}} -m venv venv"
  args:
    chdir: "{{hass_deploy_location}}"
    creates: "{{hass_deploy_location}}/venv/bin/python"
  tags: hass

- name: Make sure pip, setuptools & six are uptodate
  command: "{{hass_deploy_location}}/venv/bin/pip install -U pip setuptools six"
  args:
    chdir: "{{hass_deploy_location}}"
  tags: hass

- name: upload python requirements
  become: true
  template:
    src: requirements.txt
    dest: "{{hass_deploy_location}}/requirements.txt"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
  tags: hass

- name: install application
  pip:
    virtualenv: "{{hass_deploy_location}}/venv/"
    requirements: "{{hass_deploy_location}}/requirements.txt"
    extra_args: "--pre --upgrade -i {{devpi_index_url}}"
  notify: restart homeassistant
  tags: hass

- name: configure homeassistant
  become: true
  template:
    dest: "{{hass_data_location}}/configuration.yaml"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0664"
    src: configuration.yaml
  notify: restart homeassistant
  tags: hass

- name: configure supervisor
  become: yes
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/homeassistant.conf
    mode: "0644"
  tags: hass

- name: ensure homeassistant is running
  supervisorctl:
    name: homeassistant
    state: started
  tags: hass
