---
- name: create deployment location
  become: true
  file:
    dest: "{{hass_deploy_location}}"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory

- name: create data location
  become: true
  file:
    dest: "{{hass_data_location}}"
    owner: "{{run_user}}"
    group: "{{run_user}}"
    mode: "0750"
    state: directory

- name: init virtualenv in deployment location
  command: "{{python_interpreter}} -m venv venv"
  args:
    chdir: "{{hass_deploy_location}}"
    creates: "{{hass_deploy_location}}/venv/bin/python"

- name: Make sure pip, setuptools & six are uptodate
  command: "{{hass_deploy_location}}/venv/bin/pip install -U pip setuptools six"
  args:
    chdir: "{{hass_deploy_location}}"

- name: upload python requirements
  become: true
  copy:
    dest: "{{hass_deploy_location}}/requirements.txt"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
    content: |
      pip==9.0.1
      homeassistant==0.38.2
      aiohttp_cors==0.5.0  # requirement of HTTP component
      phue==0.9  # requirement of Philips Hue component
      SoCo==0.12  # requirement of Sonos component

- name: install application
  pip:
    virtualenv: "{{hass_deploy_location}}/venv/"
    requirements: "{{hass_deploy_location}}/requirements.txt"
    extra_args: "--pre --upgrade -i {{devpi_index_url}}"
  notify: restart nuimo_hass
  tags: update_hass

- name: configure homeassistant
  become: true
  template:
    dest: "{{hass_data_location}}/configuration.yaml"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
    src: configuration.yaml
  notify: restart nuimo_hass
  tags: update_hass

- name: configure supervisor
  become: yes
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/nuimo_hass.conf
    mode: "0644"
  tags: update_hass

- name: ensure supervisord is running
  service:
    name: supervisor
    state: running
    enabled: true
  tags: update_hass

- name: ensure homeassistant is running
  supervisorctl:
    name: nuimo_hass
    state: started
  tags: update_hass
