git:
  depth: 100
sudo: false
language: python
python:
  - "3.5"
env:
  - LINUX_WITHOUT_DBUS=1
install: pip install tox-travis
before_script: cd application
script: tox
after_success:
  - ./travis_after_success.sh