---
- name: reload supervisord
  raw: "supervisorctl reload"

- name: restart senic_hub
  supervisorctl:
    name: senic_hub
    state: restarted

- name: restart wifi_setup
  supervisorctl:
    name: wifi_setup
    state: restarted
