---
- name: reload supervisord
  raw: "supervisorctl reload"

- name: restart nuimo_hub
  supervisorctl:
    name: nuimo_hub
    state: restarted

- name: restart dbus
  service:
    name: dbus
    state: restarted
