---
- name: create deployment location
  become: true
  file:
    dest: "{{nuimoapp_deploy_location}}"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory

- name: create data location
  become: true
  file:
    dest: "{{nuimoapp_data_location}}"
    owner: "{{run_user}}"
    group: "{{run_user}}"
    mode: "0750"
    state: directory

- name: give {{run_user}} access to bluez dbus
  become: true
  template:
    dest: "/etc/dbus-1/system.d/bluetooth.conf"
    owner: root
    group: root
    mode: "0644"
    src: bluetooth.conf
  notify: restart dbus

- name: init virtualenv in deployment location
  command: "{{python_interpreter}} -m venv venv"
  args:
    chdir: "{{nuimoapp_deploy_location}}"
    creates: "{{nuimoapp_deploy_location}}/venv/bin/python"
  become: yes
  become_user: "{{build_user}}"

- name: Make sure pip & setuptools are up to date
  command: "{{nuimoapp_deploy_location}}/venv/bin/pip install --upgrade pip setuptools"
  become: yes
  become_user: "{{build_user}}"

- name: upload python requirements
  become: true
  copy:
    dest: "{{nuimoapp_deploy_location}}/requirements.txt"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
    content: |
      senic.nuimo-app

- name: install application
  pip:
    virtualenv: "{{nuimoapp_deploy_location}}/venv/"
    requirements: "{{nuimoapp_deploy_location}}/requirements.txt"
    extra_args: "--pre --upgrade -i {{devpi_index_url}}"
  become: yes
  become_user: "{{build_user}}"

- name: enable virtualenv to access the system packages
  lineinfile:
    dest: "{{nuimoapp_deploy_location}}/venv/pyvenv.cfg"
    regexp: '(include-system-site-packages = )(false)'
    line: '\1true'
    backrefs: yes

- name: configure supervisor
  become: yes
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/nuimo_app.conf
    mode: "0644"

- name: ensure supervisord is running
  service:
    name: supervisor
    state: running
    enabled: true

- name: load supervisor nuimo app config
  supervisorctl:
    name: nuimo_app
    state: stopped
