---
- name: create deployment location
  become: true
  file:
    dest: "{{nuimoapp_deploy_location}}"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory

- name: create data location
  become: true
  file:
    dest: "{{nuimoapp_data_location}}"
    owner: "{{run_user}}"
    group: "{{run_user}}"
    mode: "0750"
    state: directory

- name: give {{run_user}} access to bluez dbus
  become: true
  template:
    dest: "/etc/dbus-1/system.d/bluetooth.conf"
    owner: root
    group: root
    mode: "0644"
    src: bluetooth.conf
  notify: restart dbus

- name: init virtualenv in deployment location
  command: "{{python_interpreter}} -m venv venv"
  args:
    chdir: "{{nuimoapp_deploy_location}}"
    creates: "{{nuimoapp_deploy_location}}/venv/bin/python"

- name: upload python requirements
  become: true
  copy:
    dest: "{{nuimoapp_deploy_location}}/requirements.txt"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
    content: |
      pip==9.0.1
      nuimo==0.1.0
      websocket-client==0.40.0
      nuimo-app

- name: install application
  pip:
    virtualenv: "{{nuimoapp_deploy_location}}/venv/"
    requirements: "{{nuimoapp_deploy_location}}/requirements.txt"
    extra_args: "--pre --upgrade -i {{devpi_index_url}}"
  notify: restart nuimo app

- name: enable virtualenv to access the system packages
  lineinfile:
    dest: "{{nuimoapp_deploy_location}}/venv/pyvenv.cfg"
    regexp: "include-system-site-packages = false"
    line: "include-system-site-packages = true"

- name: configure nuimo_app
  become: true
  template:
    dest: "{{nuimoapp_data_location}}/nuimo_app.cfg"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0644"
    src: nuimo_app.cfg
  notify: restart nuimo app

- name: configure supervisor
  become: yes
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/nuimo_app.conf
    mode: "0644"
  notify: reload supervisord

- name: ensure supervisord is running
  service:
    name: supervisor
    state: running
    enabled: true
