---
- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - avahi-daemon
    - python3
    - wpasupplicant
    - wireless-tools
    - supervisor
    - python3-venv
    - python3-dbus
    - libffi-dev
    - libssl-dev
    - lighttpd

