---
- name: Uninstall system's dhcpcd5 because we're using isc-dhcp-client
  apt:
      name: dhcpcd5
      purge: yes
      state: absent

- name: Uninstall system's dhcpcd because we're using isc-dhcp-client
  apt:
      name: dhcpcd
      purge: yes
      state: absent

- name: Uninstall openresolv because we manage /etc/resolve.conf ourselves
  apt:
      name: openresolv
      purge: yes
      state: absent

# - name: Disable system's dhcpd because we'll controll it with supervisor
#   service:
#     name: dhcpd
#     state: installed

- name: Make sure DHCP server is installed
  apt:
    name: isc-dhcp-server
    state: installed

- name: Make sure DHCP service is *not* running
  service:
    name: isc-dhcp-server
    state: stopped
    enabled: no

- name: configure DHCP server interfaces
  template:
    src: isc-dhcp-server_defaults
    dest: /etc/default/isc-dhcp-server
    owner: root
    mode: "0644"

- name: configure DHCP server network
  template:
    src: isc-dhcp-server_config
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    mode: "0644"
