---
# these are the platform specific setup steps for the hub on
# an ubuntu or debian like system
# - include: dhcp.yml
#   tags: dhcp

- name: configure supervisor programs
  template:
    src: "{{item}}_supervisor.conf"
    dest: "/etc/supervisor/conf.d/{{item}}.conf"
    owner: root
    mode: "0644"
  with_items:
    - device_discovery
    - nuimo_app
    - bluenet
    - netwatch
#  notify: reload supervisord
  tags: supervisor

- include: ntp.yml
  tags: time
