---
# these are the platform specific setup steps for the hub on
# an ubuntu or debian like system
# - include: dhcp.yml
#   tags: dhcp

- name: allow run user to setup wifi
  template:
    src: sudo_nuimo_wifi
    dest: /etc/sudoers.d/010_nuimo_wifi
    owner: root
    mode: "0755"
    validate: visudo -cf %s
  tags: wifi

- name: configure supervisor programs
  template:
    src: "{{item}}_supervisor.conf"
    dest: "/etc/supervisor/conf.d/{{item}}.conf"
    owner: root
    mode: "0644"
  with_items:
    - device_discovery
    - nuimo_app
    - bluenet
#  notify: reload supervisord
  tags: supervisorconfig

- include: ntp.yml
  tags: time

- name: configure hostname
  copy:
    content: "senic-hub-{{ploy_hostname}}"
    dest: "/etc/hostname"
    owner: root
    group: root
    mode: "0644"
  notify: restart hostname service
  tags: hostname
