---
- name: restart wlan0
  raw: "ifdown {{ploy_wlan0}} && ifup {{ploy_wlan0}}"
  args:
    executable: /bin/bash

- name: restart wlan1
  raw: "ifdown {{ploy_wlan1}} && ifup {{ploy_wlan1}}"
  when: ploy_wlan0 != ploy_wlan1
  args:
    executable: /bin/bash

- name: restart avahi
  service:
    name: avahi-daemon
    state: restarted

- name: restart httpd
  service:
    name: lighttpd
    state: restarted

- name: reload supervisord
  raw: "supervisorctl reload"

- name: restart supervisor service
  service:
    name: supervisor
    state: restarted

- name: restart senic_hub
  supervisorctl:
    name: senic_hub
    state: restarted
